<?php /** Standalone printable report (browser print → PDF). No layout. */ ?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Attendance Report · <?= $e($schoolName) ?></title>
  <style>
    body { font-family: 'Inter', 'Segoe UI', sans-serif; color: #1e293b; margin: 32px; font-size: 13px; }
    h1 { font-size: 20px; margin: 0; } h2 { font-size: 14px; color: #64748b; font-weight: 400; margin: 4px 0 18px; }
    table { width: 100%; border-collapse: collapse; margin-top: 14px; }
    th, td { border: 1px solid #cbd5e1; padding: 6px 8px; text-align: left; }
    th { background: #f1f5f9; font-size: 11px; text-transform: uppercase; }
    .summary { display: flex; gap: 20px; margin: 10px 0; }
    .summary div { border: 1px solid #cbd5e1; border-radius: 8px; padding: 8px 16px; }
    .footer { margin-top: 24px; color: #64748b; font-size: 11px; }
    @media print { .no-print { display: none; } }
  </style>
</head>
<body>
  <h1><?= $e($schoolName) ?></h1>
  <h2>Attendance Report ·
    <?= $e($filters['date_from'] ?? '') ?> to <?= $e($filters['date_to'] ?? '') ?> ·
    Generated by <?= $e($currentUser['username'] ?? '') ?> on <?= $e(date('Y-m-d H:i')) ?></h2>

  <div class="summary">
    <?php foreach ($summary as $label => $total): ?>
      <div><strong><?= $e($label) ?>:</strong> <?= $e($total) ?></div>
    <?php endforeach; ?>
    <div><strong>Total:</strong> <?= count($rows) ?></div>
  </div>

  <button class="no-print" onclick="window.print()">Print</button>

  <table>
    <thead><tr>
      <th>Date</th><th>Time</th><th>Student #</th><th>Student</th><th>Section</th>
      <th>Subject</th><th>Room</th><th>Teacher</th><th>Status</th>
    </tr></thead>
    <tbody>
    <?php if ($rows === []): ?>
      <tr><td colspan="9" style="text-align:center;color:#64748b;">No records found.</td></tr>
    <?php endif; ?>
    <?php foreach ($rows as $row): ?>
      <tr>
        <td><?= $e(substr((string) $row['recorded_at'], 0, 10)) ?></td>
        <td><?= $e(substr((string) $row['recorded_at'], 11, 8)) ?></td>
        <td><?= $e($row['student_number']) ?></td>
        <td><?= $e($row['student_name']) ?></td>
        <td><?= $e($row['section_name']) ?></td>
        <td><?= $e($row['subject_name']) ?></td>
        <td><?= $e($row['room_number']) ?></td>
        <td><?= $e($row['teacher_name']) ?></td>
        <td><?= $e($row['status_name']) ?></td>
      </tr>
    <?php endforeach; ?>
    </tbody>
  </table>
  <p class="footer">L-SIAMS — Local IoT-Based Multi-Layer Secured Attendance Monitoring System</p>
</body>
</html>
