#pragma once
// =====================================================================
// L-SIAMS classroom terminal — device configuration.
// Provision per device: set DEVICE_ID and paste the API key generated by
// the server's Device Management page (shown exactly once).
// =====================================================================

// ---- Identity --------------------------------------------------------
#define DEVICE_ID        "DEV-001"
#define API_KEY          "PASTE-GENERATED-API-KEY-HERE"
#define FIRMWARE_VERSION "1.0.0"

// ---- Network ---------------------------------------------------------
#define WIFI_SSID        "LSIAMS-NET"
#define WIFI_PASSWORD    "change-this-wifi-password"
#define SERVER_HOST      "192.168.1.10"     // static LAN IP of the server
// Production: 443 + TLS. Bench testing against the PHP dev server:
// set SERVER_PORT 8000 and USE_TLS false.
#define SERVER_PORT      443
#define USE_TLS          true
// Self-signed deployments: paste the server certificate (PEM) here and the
// client will pin it. Leave empty ONLY for bench testing.
static const char SERVER_CA_CERT[] PROGMEM = R"PEM(
)PEM";

// ---- Pins (ESP32 DevKit V1) -------------------------------------------
#define PIN_RC522_SS     5
#define PIN_RC522_RST    27
// RC522 uses VSPI: SCK=18, MISO=19, MOSI=23
#define PIN_R307_RX      16   // ESP32 RX2  <- R307 TX
#define PIN_R307_TX      17   // ESP32 TX2  -> R307 RX
#define PIN_BUZZER       25
#define PIN_LED_GREEN    32
#define PIN_LED_YELLOW   33
#define PIN_LED_RED      26
#define PIN_LED_BLUE     14   // WiFi status
// OLED SSD1306 on I2C: SDA=21, SCL=22, addr 0x3C

// ---- Behaviour ---------------------------------------------------------
#define HEARTBEAT_INTERVAL_MS     30000UL
#define TIME_SYNC_INTERVAL_MS     (6UL * 60UL * 60UL * 1000UL)  // 6 hours
#define SYNC_RETRY_INTERVAL_MS    15000UL
#define OFFLINE_QUEUE_LIMIT       500
#define FINGERPRINT_MAX_FAILURES  5
#define FINGERPRINT_LOCK_MS       (5UL * 60UL * 1000UL)
#define RFID_DEBOUNCE_MS          2500UL
#define HTTP_TIMEOUT_MS           8000
