<?php
declare(strict_types=1);

namespace App\Core;

/**
 * HTTP response builder.
 *
 * All API payloads flow through json() so the envelope defined in Part 8/20.2
 * ({success, code, message, data}) is structurally guaranteed rather than
 * re-typed at each call site.
 */
final class Response
{
    private int $status = 200;
    /** @var array<string,string> */
    private array $headers = [];
    private string $content = '';
    /** @var list<array{0:string,1:string,2:array<string,mixed>}> */
    private array $cookies = [];
    private bool $skipSecurityHeaders = false;

    public static function make(string $content = '', int $status = 200): self
    {
        $response          = new self();
        $response->content = $content;
        $response->status  = $status;

        return $response;
    }

    public static function html(string $html, int $status = 200): self
    {
        return self::make($html, $status)->withHeader('Content-Type', 'text/html; charset=UTF-8');
    }

    public static function text(string $text, int $status = 200): self
    {
        return self::make($text, $status)->withHeader('Content-Type', 'text/plain; charset=UTF-8');
    }

    /** @param array<string,mixed>|list<mixed> $data */
    public static function json(array $data, int $status = 200): self
    {
        $encoded = json_encode(
            $data,
            JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_INVALID_UTF8_SUBSTITUTE
        );

        return self::make($encoded === false ? '{"success":false,"code":"ENCODING_ERROR"}' : $encoded, $status)
            ->withHeader('Content-Type', 'application/json; charset=UTF-8')
            ->withHeader('X-Content-Type-Options', 'nosniff');
    }

    /** Standard success envelope. @param array<string,mixed>|list<mixed> $data */
    public static function ok(array $data = [], string $message = 'OK', int $status = 200): self
    {
        return self::json([
            'success' => true,
            'code'    => 'OK',
            'message' => $message,
            'data'    => $data,
        ], $status);
    }

    /** Standard failure envelope. @param array<string,mixed> $data */
    public static function fail(string $code, string $message, int $status = 400, array $data = []): self
    {
        return self::json([
            'success' => false,
            'code'    => $code,
            'message' => $message,
            'data'    => $data,
        ], $status);
    }

    /** @param array<string,list<string>> $errors */
    public static function validationError(array $errors, string $message = 'Validation failed.'): self
    {
        return self::json([
            'success' => false,
            'code'    => 'VALIDATION_ERROR',
            'message' => $message,
            'data'    => ['errors' => $errors],
        ], 422);
    }

    public static function redirect(string $location, int $status = 302): self
    {
        return self::make('', $status)->withHeader('Location', $location);
    }

    public static function noContent(): self
    {
        return self::make('', 204);
    }

    /** Streams a file from disk with a download disposition. */
    public static function download(string $path, string $filename, string $mime = 'application/octet-stream'): self
    {
        $response                      = new self();
        $response->status              = 200;
        $response->content             = (string) file_get_contents($path);
        $response->headers['Content-Type']        = $mime;
        $response->headers['Content-Disposition'] = 'attachment; filename="' . self::sanitizeFilename($filename) . '"';
        $response->headers['Content-Length']      = (string) strlen($response->content);
        $response->headers['Cache-Control']       = 'private, no-store';

        return $response;
    }

    /** Sends generated bytes without ever touching the filesystem (provisioning files). */
    public static function attachment(string $content, string $filename, string $mime = 'application/octet-stream'): self
    {
        $response                                 = new self();
        $response->status                         = 200;
        $response->content                        = $content;
        $response->headers['Content-Type']        = $mime;
        $response->headers['Content-Disposition'] = 'attachment; filename="' . self::sanitizeFilename($filename) . '"';
        $response->headers['Content-Length']      = (string) strlen($content);
        $response->headers['Cache-Control']       = 'private, no-store, no-cache, must-revalidate';
        $response->headers['Pragma']              = 'no-cache';

        return $response;
    }

    private static function sanitizeFilename(string $filename): string
    {
        $clean = preg_replace('/[^A-Za-z0-9._-]/', '_', $filename) ?? 'download';

        return substr($clean, 0, 120);
    }

    public function withHeader(string $name, string $value): self
    {
        $this->headers[$name] = $value;

        return $this;
    }

    /** @param array<string,mixed> $options */
    public function withCookie(string $name, string $value, array $options = []): self
    {
        $this->cookies[] = [$name, $value, $options];

        return $this;
    }

    public function withStatus(int $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function withoutSecurityHeaders(): self
    {
        $this->skipSecurityHeaders = true;

        return $this;
    }

    public function status(): int
    {
        return $this->status;
    }

    public function content(): string
    {
        return $this->content;
    }

    /** @return array<string,string> */
    public function headers(): array
    {
        return $this->headers;
    }

    public function send(): void
    {
        if (!headers_sent()) {
            http_response_code($this->status);

            if (!$this->skipSecurityHeaders) {
                /** @var array<string,string> $securityHeaders */
                $securityHeaders = Config::get('security.headers', []);
                foreach ($securityHeaders as $name => $value) {
                    // HSTS only means anything over TLS, and asserting it on a
                    // plain-HTTP dev box just breaks the developer's browser.
                    if ($name === 'Strict-Transport-Security' && !self::isHttps()) {
                        continue;
                    }
                    header($name . ': ' . Csp::apply((string) $value));
                }
                header_remove('X-Powered-By');
            }

            foreach ($this->headers as $name => $value) {
                header($name . ': ' . $value, true);
            }

            foreach ($this->cookies as [$name, $value, $options]) {
                setcookie($name, $value, $options);
            }
        }

        echo $this->content;
    }

    private static function isHttps(): bool
    {
        return (($_SERVER['HTTPS'] ?? '') !== '' && strtolower((string) $_SERVER['HTTPS']) !== 'off')
            || (int) ($_SERVER['SERVER_PORT'] ?? 0) === 443;
    }
}
